// add doner data
export const CREATE_DONER_DATA_START="CREATE_DONER_DATA_START"
export const CREATE_DONER_DATA_SUCCESS="CREATE_DONER_DATA_SUCCESS"
export const CREATE_DONER_DATA_ERROR="CREATE_DONER_DATA_ERROR"